### ISSUE TITLE
Implement Sidebar Link Component

### ISSUE THREAD

**Issue by Pr0x1m4** [PalisadoesFoundation/insite-ui#1]
Implement navbar component from exisiting `garnet` project 

![2018-06-24-131945_3840x2160_scrot](https://user-images.githubusercontent.com/4820517/41822317-5189cc20-77b3-11e8-9190-f69aca385d36.png)

**Comment by tevon456** [comment]
Does it have to match the design spec of the last project seeing that we dropped the name garnet can the garnet be removed?

**Comment by Pr0x1m4** [comment]
Use updated spec, this issue is really old.
https://www.figma.com/file/dDWjQgqxF2TkxDFHe7j5AmCC/insite?node-id=0%3A1

**Comment by Pr0x1m4** [comment]
A better issue, would be just to implement the styled links for the sidebar
